{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[],"authorship_tag":"ABX9TyNtLsEycV5Rm7ONX44vz1Cc"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"code","execution_count":null,"metadata":{"id":"9wKdMi8i2iAu"},"outputs":[],"source":["\"\"\"checks all of the follows from this day one week ago, and unfollows any users that did not follow back.\n","  logging should record stats of follows-follow backs from that day as well as number of accounts that were deleted.\n","  Should consume as much of the list in the s3 bucket as possible, and return early if there's nothing in the bucket to delete.\n","  After processing as much as possible the function will log how much it did, how much is remaining, and it will save in the dynamodb deletions stats what the current counts of everything are.\n","  When the s3 bucket is completely emptied out, the s3 object will be deleted, and the dynamodb deletions stats will be finished and logged for the sum of the day.\n","\n","  Args:\n","    None\n","  Returns:\n","    None\n","\"\"\""]},{"cell_type":"code","source":["pip install boto3"],"metadata":{"id":"nAWMbFq6CwOY"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["pip install atproto"],"metadata":{"id":"EamVwlrKC2vD"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["# import colab secrets to store login credentials\n","from google.colab import userdata\n","\n","# aws stuff\n","import boto3\n","from botocore.exceptions import ClientError\n","# json necessary to parse secret string, and write/read s3 objects\n","import json\n","\n","# datetime is necessary for our ddb and s3 schema\n","import datetime\n","import zoneinfo\n","\n","# for logging\n","import base64\n","import requests\n","\n","\n","# import bluesky api\n","from atproto import Client\n","# this is the exception that is raised when we try to find a\n","from atproto.exceptions import BadRequestError"],"metadata":{"id":"ezqurP0IC662"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["AWS_KEY = userdata.get('aws_access_key')\n","AWS_SECRET_KEY = userdata.get('aws_secret_access_key')\n","REGION = userdata.get('aws_region')\n","SECRETS_ID = userdata.get('aws_secretsmanager_id')\n","\n","DDB = 'dynamodb'\n","S3 = 's3'\n","DDB_TABLE = 'rickybot-ddb'\n","S3_BUCKET = 'rickybot-s3'\n","DDB_DELSTATS_KEY = 'DEL-STATS'\n","DDB_ATTR_PROCESSED = 'PROCESSED'\n","DDB_ATTR_DNE = 'DNE'\n","DDB_ATTR_FOLLOWBACKS = 'FOLLOWBACKS'\n","DDB_ATTR_NOFOLLOWBACK = 'NO-FOLLOWBACK'\n","\n","PRIMARY_KEY = 'DOW' # the dynamodb table's primary key. there is no sort key\n","DOW_KEYS = {\n","    'Sunday': 'SUN',\n","    'Monday': 'MON',\n","    'Tuesday': 'TUE',\n","    'Wednesday': 'WED',\n","    'Thursday': 'THU',\n","    'Friday': 'FRI+SAT',\n","    'Saturday': 'FRI+SAT'\n","}\n","USER_TIMEZONE = \"US/Eastern\"\n","\n","FILE_PATH = \"LOGGING_DEL_02.txt\"\n","BRANCH = \"main\"\n","\n","MY_DID = 'did:plc:ktkc7jfakxzjpooj52ffc6ra'"],"metadata":{"id":"irW0GLzjDbV1"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["# get the day of the week so we know what dynamodb key to pull from and which bucket to aggregate to\n","# doing this first because we do not run this on saturday and can bail out early if we get into this code for some reason\n","# also we are running this at about 1am, the following day after all runs have concluded for the previous. so we're aggregating the previous day's results\n","cur_timestamp = datetime.datetime.now(zoneinfo.ZoneInfo(USER_TIMEZONE))\n","dow = cur_timestamp.strftime(\"%A\")\n","str_timestamp = str(cur_timestamp) # we'll need this to use as the attribute for ddb\n","\n","if dow == 'Saturday':\n","  print(\"it's Saturday, you shouldn't be here.\")\n","  # return early\n","\n","# use the day of the week to pull up the corresponding key for our dynamodb entries and our s3 bucket\n","s3_key = DOW_KEYS[dow]\n","print(s3_key)"],"metadata":{"id":"JFjkEYWXDwhu"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["# connect to aws\n","try:\n","  aws_session = boto3.Session(\n","          aws_access_key_id = AWS_KEY,\n","          aws_secret_access_key = AWS_SECRET_KEY,\n","          region_name = REGION\n","      )\n","except:\n","  print('failed to begin AWS session')\n","  # return with error\n","  # this is the only error that we can't log to github, because we never got the credentials"],"metadata":{"id":"49F-j2rSESoZ"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["# then connect to secrets manager\n","try:\n","  secrets_client = aws_session.client('secretsmanager')\n","  secret_value = secrets_client.get_secret_value(SecretId=SECRETS_ID)\n","  secret_string = secret_value['SecretString']\n","  secret_map = json.loads(secret_string)\n","except:\n","  print('failed to reach aws secrets manager')\n","  # return with error"],"metadata":{"id":"C8bw09lYETaq"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["# create constants from the values in the secrets manager\n","BSKY_USERNAME = secret_map['bsky_username']\n","BSKY_PASSWORD = secret_map['bsky_password']\n","GITHUB_TOKEN = secret_map['github_token']\n","GITHUB_REPO = secret_map['github_user/repo']\n","HUGGING_TOKEN = secret_map['hugging_token']"],"metadata":{"id":"MwIr78cJEZs0"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["# before the program starts let's set up the logging function so we can insert it at any point where our program could break\n","def logging_deletions(logging_text):\n","  # LOGGING ALL THE CHANGES TO OUR LOGGING FILE IN GITHUB\n","  datetime_object = datetime.datetime.fromtimestamp(cur_timestamp.timestamp())\n","  date_only = str(datetime_object.date())\n","  commit_message = \"Logging follow deletions on \" + date_only\n","\n","\n","  # Step 1: Get the file's current content and SHA\n","  url = f\"https://api.github.com/repos/{GITHUB_REPO}/contents/{FILE_PATH}\"\n","  headers = {\"Authorization\": f\"token {GITHUB_TOKEN}\"}\n","  response = requests.get(url, headers=headers)\n","  response_json = response.json()\n","\n","  # Decode the content of the file\n","  file_sha = response_json[\"sha\"]\n","  content = base64.b64decode(response_json[\"content\"]).decode(\"utf-8\")\n","\n","  # Step 2: Modify the file content\n","  new_content = content + date_only + ': ' + logging_text + '\\n'\n","  encoded_content = base64.b64encode(new_content.encode(\"utf-8\")).decode(\"utf-8\")\n","\n","  # Step 3: Push the updated content\n","  data = {\n","      \"message\": commit_message,\n","      \"content\": encoded_content,\n","      \"sha\": file_sha,\n","      \"branch\": BRANCH,\n","  }\n","  update_response = requests.put(url, headers=headers, json=data)\n","\n","  if update_response.status_code == 200:\n","      print(\"Logging file updated successfully! Here's what was added to the logs:\")\n","      print(date_only + \": \" + logging_text)\n","  else:\n","      print(f\"Error: {update_response.json()}\")"],"metadata":{"id":"yPAEGVGwEeA6"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["# initialize dynamodb and s3\n","try:\n","  dynamodb = aws_session.resource(DDB)\n","  table = dynamodb.Table(DDB_TABLE)\n","except:\n","  print('ERROR - failed to get dynamo db table')\n","  logging_deletions('ERROR - failed to get dynamo db table')\n","  # return with error\n","try:\n","  s3 = aws_session.client(S3)\n","  buckets = s3.list_buckets()\n","  bucket = s3.list_objects_v2(Bucket=S3_BUCKET)\n","except:\n","  print('ERROR - failed to get s3 bucket')\n","  logging_deletions('ERROR - failed to get s3 bucket')\n","  # return with error"],"metadata":{"id":"s6BXNqwDE6h9"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["# pull the object from s3 - if there is nothing in there we can return early\n","try:\n","  s3.head_object(Bucket=S3_BUCKET, Key=s3_key)\n","  print(\"Object existed in s3 bucket.\")\n","  response = s3.get_object(Bucket=S3_BUCKET, Key=s3_key)\n","  # creates a list from the json info in the s3 bucket\n","  old_follows = json.loads(response[\"Body\"].read())\n","  print(old_follows, type(old_follows))\n","except s3.exceptions.ClientError as e:\n","  if e.response[\"Error\"][\"Code\"] == \"404\": # object was not found at the key\n","    print('There was no users list found in s3. Terminating function call.')\n","    # RETURN\n","  else:\n","    print(\"ERROR - failed to get previous follows list from s3 bucket\")\n","    logging_deletions(\"ERROR - failed to get previous follows list from s3 bucket\")"],"metadata":{"id":"7SRj5Z_BFEyI"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["# and now we can log into the bluesky client\n","try:\n","  client = Client()\n","  client.login(BSKY_USERNAME, BSKY_PASSWORD)\n","except:\n","  err = 'ERROR - failed to log in to the bluesky client'\n","  print(err)\n","  logging_deletions(err)\n","  # return here, cannot proceed without bluesky"],"metadata":{"id":"V-rQEoaKFFBD"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["# initialize our deletion stats for our logging and dynamodb record\n","processed_count = 0\n","failed_to_delete = [] # if any fail we can add them back in and retry later\n","count_users_dne = 0 # if we fail to find on lookup the account does not exist anymore\n","followed_back = 0\n","no_followback = 0\n","finished_deleting = False # flag to let us know if we can delete the running deletion stats\n","error_count = 0\n","\n","# now go through the followers, check if they still exist, see if they followed back, delete if necessary\n","for user_did in old_follows:\n","  processed_count += 1\n","  if user_did == MY_DID:\n","    # this shouldn't happen but we'll cover it anyway\n","    continue\n","  # first we have to try to get the profile of the user\n","  try:\n","    user_profile = client.get_profile(actor=user_did)\n","  except BadRequestError as e:\n","    # if we get a bad request error it means that the profile was either banned or deleted. Nothing else to do with them, but I want to keep track of these.\n","    # we could really validate this by using the next line of code, but it's overkill - I don't want to get hyperspecific\n","    # if e.response.content.message == 'Profile not found':\n","    count_users_dne += 1\n","  except:\n","    # if we had a general exception then we should retry this user later, probably just timed out or something.\n","    failed_to_delete.append(user_did)\n","    error_count += 1\n","    if error_count > 3: # something's going wrong with this run, either rate limiting or timing out for some reason\n","      break\n","\n","  user_didnt_followback = True if user_profile.viewer.followed_by == None else False\n","  if user_didnt_followback:\n","    no_followback += 1\n","    try:\n","      follow_uri = user_profile.viewer.following\n","      if follow_uri != None: # maybe I manually unfollowed\n","        client.delete_follow(follow_uri)\n","    except:\n","      # something went wrong and we failed to delete this user, it's extremely rare for this to happen unless you're just rate limited, so save this for later\n","      failed_to_delete.append(user_did)\n","      error_count += 1\n","      if error_count > 3: # we're probably getting rate limited, so stop processing users\n","        break\n","    finally:\n","      if no_followback >= 3500: # this is a hard cap on deletions so you don't get rate limited.\n","        break\n","  else:\n","    followed_back += 1\n","\n","# ok so we're out of the loop and here's what we need to do\n","# log our progress through the list of deletions.\n","logging_deletions(f'Processed {processed_count} users from the list of {len(old_follows)}.{\"\" if len(failed_to_delete) == 0 else f\" {len(failed_to_delete)} failures were encountered and need to be retried.\"} From this batch of deletions {followed_back} users followed back, {no_followback} did not follow back and were deleted, and {count_users_dne} accounts no longer exist.')\n","# add any users that we failed to delete back to the end of the list. hopefully this should usually be 0\n","old_follows.extend(failed_to_delete)\n","# now we check to see if we made it to the end of the list.\n","if processed_count >= len(old_follows):\n","  finished_deleting = True\n","  # now delete the s3 object\n","  try:\n","    s3.delete_object(Bucket=S3_BUCKET, Key=s3_key)\n","  except Exception as e:\n","    err = f'ERROR - failed to delete the list of follows from the s3 bucket: {e}'\n","    print(err)\n","    logging_deletions(err)\n","else:\n","  # take a slice from wherever we got to until the end of the list, and then we'll stick that back into s3\n","  leftover_follows = old_follows[processed_count : ]\n","  try:\n","    s3.put_object(\n","        Bucket=S3_BUCKET,\n","        Key=s3_key,\n","        Body=json.dumps(leftover_follows),\n","        ContentType=\"application/json\"\n","    )\n","    logging_deletions(f'successfully uploaded the list of remaining follows to check to s3.')\n","  except Exception as e:\n","    err = f\"ERROR - failed to upload list of leftover follows to s3: {e}\"\n","    print(err)\n","    logging_deletions(err)\n","\n","# delete s3 if nothing left to put in\n","# do logging here"],"metadata":{"id":"qRsMSpXwFi2P","colab":{"base_uri":"https://localhost:8080/","height":106},"executionInfo":{"status":"error","timestamp":1739970246697,"user_tz":300,"elapsed":50,"user":{"displayName":"Tyler Crews","userId":"08967755967182590100"}},"outputId":"ef61a7d4-2df0-4bcb-9a39-312770e87c7b"},"execution_count":1,"outputs":[{"output_type":"error","ename":"SyntaxError","evalue":"invalid syntax (<ipython-input-1-2423fff44e4c>, line 27)","traceback":["\u001b[0;36m  File \u001b[0;32m\"<ipython-input-1-2423fff44e4c>\"\u001b[0;36m, line \u001b[0;32m27\u001b[0m\n\u001b[0;31m    if !follows_you:\u001b[0m\n\u001b[0m       ^\u001b[0m\n\u001b[0;31mSyntaxError\u001b[0m\u001b[0;31m:\u001b[0m invalid syntax\n"]}]},{"cell_type":"code","source":["# pull up dynamodb, see if there were old stats, and add them to our current stats\n","try:\n","  ddb_response = table.get_item(\n","      Key={'DOW': DDB_DELSTATS_KEY},\n","  )\n","except Exception as e:\n","  print(f\"ERROR - failed to check ddb key's existence: {e}\")\n","  logging_deletions(f\"ERROR - failed to check ddb key's existence: {e}\")\n","\n","print('ddb response:', ddb_response)\n","# it's not a problem if there was nothing in the response, it just means this was the first deletion of the day\n","if 'Item' in ddb_response:\n","  processed_count += ddb_response['Item'][DDB_ATTR_PROCESSED]\n","  count_users_dne += ddb_response['Item'][DDB_ATTR_DNE]\n","  followed_back += ddb_response['Item'][DDB_ATTR_FOLLOWBACKS]\n","  no_followback += ddb_response['Item'][DDB_ATTR_NOFOLLOWBACK]\n","\n","  # after finishing iterating through all of the attributes we can delete this key from the dynamodb to clear out all the previous runs\n","  if finished_deleting:\n","    conversion_rate = round(followed_back / (followed_back + no_followback) * 100, 2)\n","    logging_deletions(f\"Finished checking last week's follows from {s3_key} for deletions. In total there were {processed_count} follows processed. {followed_back} users followed back. {no_followback} did not follow back and were deleted. {count_users_dne} accounts no longer exist. Conversion Rate was {conversion_rate}%.\")\n","    try:\n","      table.delete_item(\n","        Key={'DOW': DDB_DELSTATS_KEY}\n","      )\n","    except Exception as e:\n","      err = f\"ERROR - failed to delete item {DDB_DELSTATS_KEY} from dynamodb: {e}\"\n","      print(err)\n","      logging_deletions(err)\n","  else:\n","    # if we're not finished deleting then we update the ddb delstats for next run\n","    try:\n","      table.update_item(\n","          Key={'DOW': DDB_DELSTATS_KEY},\n","          UpdateExpression='SET #attr1 = :val1, #attr2 = :val2, #attr3 = :val3, #attr4 = :val4',\n","          ExpressionAttributeNames={\n","              '#attr1': DDB_ATTR_PROCESSED,\n","              '#attr2': DDB_ATTR_DNE,\n","              '#attr3': DDB_ATTR_FOLLOWBACKS,\n","              '#attr4': DDB_ATTR_NOFOLLOWBACK\n","          },\n","          ExpressionAttributeValues={\n","              ':val1': processed_count,\n","              ':val2': count_users_dne,\n","              ':val3': followed_back,\n","              ':val4': no_followback\n","          }\n","      )\n","    except Exception as e:\n","      err = f'ERROR - failed to store running deletion statistics in dynamodb.\\n{e}'\n","      print(err)\n","      logging_deletions(err)"],"metadata":{"id":"ydpvvoh_HEuL"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["# for debugging, do not leave this in final code\n","print(table.scan())"],"metadata":{"id":"Gh6-nN_hH9Rf"},"execution_count":null,"outputs":[]}]}
